modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/hlysine/create_connected/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/hlysine/create_connected/main/update.json"
    displayURL="https://github.com/hlysine/create_connected"
    logoFile="create_connected_icon.png"
    credits="GitHub contributors, the Create mod Discord and redditors"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="${create_version_range}"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="create_connected.mixins.json"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"